import AVFoundation
import Foundation
import XCTest
@testable import GMPlayerKit

/// Reproduction + regression guard for the resource-loader "freezes after the first
/// fragment" bug. The earlier harness gave false greens because it pulled frames from
/// an AVPlayerItemVideoOutput at host time, which happily reports the first decoded-
/// ahead fragment as "playing" even when the stream stalls at the first segment
/// boundary. This test instead feeds the EXACT bytes the resource loader serves into
/// AVFoundation's own demux+decode (AVAssetReader) and asserts it decodes through the
/// WHOLE movie, not just segment 0.
///
/// Ground truth observed when broken: AVAssetReader yields ~60 frames and stops at
/// lastPTS ≈ 1.97s of a 12s movie (one 2s segment), while FFmpeg decodes all of it.
///
/// The fixture is a tiny synthetic MKV generated by ffmpeg at runtime (no checked-in
/// binary, no network). The test SKIPS only if ffmpeg is unavailable; it never skips
/// silently when it could run.
final class GMResourceLoaderDecodeTests: XCTestCase {
    private static var mkvPath: String?
    private static var ffmpegMissing = false

    override class func setUp() {
        super.setUp()
        guard let ffmpeg = findFFmpeg() else { ffmpegMissing = true
            return
        }
        let out = NSTemporaryDirectory() + "gm-rl-decode-\(UUID().uuidString).mkv"
        // 12s, 320x240, 30fps, keyframe every 30 frames (1s) so the planner makes
        // several ~2s segments. Tiny (<1MB) and fast to mux.
        // GOP of 51 frames (~1.7s @30fps) deliberately does NOT divide the 2s segment
        // target, so segment boundaries fall MID-GOP. That is what exposes the audio
        // boundary-drop bug (#akm19m): with a keyframe exactly on every boundary the
        // drop window is ~0 and the bug hides. Keep keyframes frequent enough that the
        // planner still makes several segments.
        let args = [
            "-y", "-v", "error",
            "-f", "lavfi", "-i", "testsrc2=size=320x240:rate=30:duration=12",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=12",
            "-c:v", "libx264", "-g", "51", "-keyint_min", "51", "-sc_threshold", "0",
            "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest", out,
        ]
        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: ffmpeg)
        proc.arguments = args
        do {
            try proc.run()
            proc.waitUntilExit()
            if proc.terminationStatus == 0, FileManager.default.fileExists(atPath: out) {
                mkvPath = out
            }
        } catch {
            ffmpegMissing = true
        }
    }

    override class func tearDown() {
        if let p = mkvPath { try? FileManager.default.removeItem(atPath: p) }
        super.tearDown()
    }

    private static func findFFmpeg() -> String? {
        for p in ["/opt/homebrew/bin/ffmpeg", "/usr/local/bin/ffmpeg", "/usr/bin/ffmpeg"]
            where FileManager.default.isExecutableFile(atPath: p)
        {
            return p
        }
        return nil
    }

    /// Decode the assembled fMP4 with AVFoundation and return (frameCount, lastPTS).
    private func decodeAllFrames(_ data: Data) throws -> (Int, Double) {
        let path = NSTemporaryDirectory() + "gm-assembled-\(UUID().uuidString).mp4"
        try data.write(to: URL(fileURLWithPath: path))
        defer { try? FileManager.default.removeItem(atPath: path) }

        let asset = AVURLAsset(url: URL(fileURLWithPath: path))
        let sem = DispatchSemaphore(value: 0)
        var vtrack: AVAssetTrack?
        asset.loadTracks(withMediaType: .video) { tracks, _ in vtrack = tracks?.first
            sem.signal()
        }
        _ = sem.wait(timeout: .now() + 10)
        let track = try XCTUnwrap(vtrack, "assembled fMP4 has no video track")

        let reader = try AVAssetReader(asset: asset)
        let out = AVAssetReaderTrackOutput(
            track: track,
            outputSettings: [kCVPixelBufferPixelFormatTypeKey as String: Int(kCVPixelFormatType_32BGRA)]
        )
        reader.add(out)
        reader.startReading()
        var frames = 0
        var lastPTS = 0.0
        while let sb = out.copyNextSampleBuffer() {
            lastPTS = CMSampleBufferGetPresentationTimeStamp(sb).seconds
            frames += 1
            CMSampleBufferInvalidate(sb)
        }
        return (frames, lastPTS)
    }

    /// Decode frames in a TIME RANGE starting at `seekTime` (AVAssetReader.timeRange is
    /// the headless equivalent of seeking: it forces AVFoundation to random-access into
    /// the file at that time). Returns (frameCount, firstDecodedPTS).
    private func decodeFromSeek(_ data: Data, seekTime: Double, window: Double = 3.0) throws -> (Int, Double) {
        let path = NSTemporaryDirectory() + "gm-seek-\(UUID().uuidString).mp4"
        try data.write(to: URL(fileURLWithPath: path))
        defer { try? FileManager.default.removeItem(atPath: path) }

        let asset = AVURLAsset(url: URL(fileURLWithPath: path))
        let sem = DispatchSemaphore(value: 0)
        var vtrack: AVAssetTrack?
        asset.loadTracks(withMediaType: .video) { tracks, _ in vtrack = tracks?.first
            sem.signal()
        }
        _ = sem.wait(timeout: .now() + 10)
        let track = try XCTUnwrap(vtrack, "no video track")

        let reader = try AVAssetReader(asset: asset)
        reader.timeRange = CMTimeRange(
            start: CMTime(seconds: seekTime, preferredTimescale: 600),
            duration: CMTime(seconds: window, preferredTimescale: 600)
        )
        let out = AVAssetReaderTrackOutput(
            track: track,
            outputSettings: [kCVPixelBufferPixelFormatTypeKey as String: Int(kCVPixelFormatType_32BGRA)]
        )
        reader.add(out)
        reader.startReading()
        var frames = 0
        var firstPTS = Double.nan
        while let sb = out.copyNextSampleBuffer() {
            if frames == 0 { firstPTS = CMSampleBufferGetPresentationTimeStamp(sb).seconds }
            frames += 1
            CMSampleBufferInvalidate(sb)
        }
        return (frames, firstPTS)
    }

    /// Load the assembled fMP4 as an AVURLAsset and report what AVFoundation believes
    /// the timeline is: overall duration + each track's timeRange duration.
    private func avDurations(_ data: Data) throws -> (asset: Double, video: Double, audio: Double) {
        let path = NSTemporaryDirectory() + "gm-dur-\(UUID().uuidString).mp4"
        try data.write(to: URL(fileURLWithPath: path))
        defer { try? FileManager.default.removeItem(atPath: path) }
        let asset = AVURLAsset(url: URL(fileURLWithPath: path))
        let sem = DispatchSemaphore(value: 0)
        asset.loadValuesAsynchronously(forKeys: ["duration", "tracks"]) { sem.signal() }
        _ = sem.wait(timeout: .now() + 20)
        var v = 0.0
        var a = 0.0
        for tr in asset.tracks {
            if tr.mediaType == .video { v = tr.timeRange.duration.seconds }
            if tr.mediaType == .audio { a = tr.timeRange.duration.seconds }
        }
        return (asset.duration.seconds, v, a)
    }

    /// CONTENT-LENGTH regression (the "shows 37s duration" bug): the lazy loader
    /// declares a contentLength estimate up front. If it badly UNDER-estimates (the old
    /// seg0-bitrate extrapolation was ~15x low for 4K), AVFoundation thinks the resource
    /// ends early and reports a fraction of the real duration. The declared length must
    /// be at least the real assembled size (over-declaring is safe; a read past true EOF
    /// returns clean 0).
    func testDeclaredContentLengthCoversWholeMovie() throws {
        if Self.ffmpegMissing { throw XCTSkip("ffmpeg not found; cannot generate fixture") }
        let mkv = try XCTUnwrap(Self.mkvPath, "fixture MKV was not generated")

        let session = try GMStreamSession(
            source: XCTUnwrap(GMFileByteSource(path: mkv)),
            targetSegmentSeconds: 2.0
        )
        let loader = try GMResourceLoaderDelegate(session: session)
        let declared = loader.declaredContentLength
        let actual = Int64(loader.assembledBytes.count) // forces full build
        XCTAssertGreaterThanOrEqual(
            declared, actual,
            "declared contentLength \(declared) < real assembled \(actual): AVFoundation will think the resource ends early and report a short duration"
        )
    }

    /// LAZY-INIT regression (BUG #1958b5): URL playback hung on "inspecting" forever
    /// because the loader assembled the WHOLE movie (all N segments) in init before
    /// makePlayback returned. Over a remote origin that is minutes. init must mux only
    /// the init segment + the first fragment, then build the rest on demand in serve().
    func testInitDoesNotAssembleWholeMovie() throws {
        if Self.ffmpegMissing { throw XCTSkip("ffmpeg not found; cannot generate fixture") }
        let mkv = try XCTUnwrap(Self.mkvPath, "fixture MKV was not generated")

        let session = try GMStreamSession(
            source: XCTUnwrap(GMFileByteSource(path: mkv)),
            targetSegmentSeconds: 2.0
        )
        XCTAssertGreaterThan(session.segmentCount, 3, "need several segments to prove laziness")
        let loader = try GMResourceLoaderDelegate(session: session)
        // Right after init, at most the first fragment is built (not the whole movie).
        XCTAssertLessThanOrEqual(
            loader.builtSegmentCount, 1,
            "init muxed \(loader.builtSegmentCount)/\(session.segmentCount) segments, not lazy, will hang remote URLs"
        )
    }

    /// SEEK regression (BUG #1018baf): seeking shows black while the clock keeps
    /// running. Proven cause: AVFoundation reports asset.duration ≈ 2× the real movie
    /// (the moov's per-track tkhd/mdhd durations were stamped to the full length AND
    /// the fragments contribute their own durations, so the track timeline is summed
    /// twice). The scrubber timeline is then 2× too long; seeking to e.g. 70% lands
    /// past the real end -> black video, advancing clock. Assert AVFoundation's
    /// duration matches the engine's real duration.
    func testAssetDurationMatchesRealDuration() throws {
        if Self.ffmpegMissing { throw XCTSkip("ffmpeg not found; cannot generate fixture") }
        let mkv = try XCTUnwrap(Self.mkvPath, "fixture MKV was not generated")

        let session = try GMStreamSession(
            source: XCTUnwrap(GMFileByteSource(path: mkv)),
            targetSegmentSeconds: 2.0
        )
        let real = session.duration
        let loader = try GMResourceLoaderDelegate(session: session)
        let d = try avDurations(loader.assembledBytes)

        XCTAssertEqual(
            d.asset, real, accuracy: max(1.0, real * 0.05),
            "AVFoundation asset.duration=\(d.asset)s but real=\(real)s (ratio \(d.asset / real)), doubled timeline => seek lands past content => black"
        )
        XCTAssertEqual(
            d.video, real, accuracy: max(1.0, real * 0.05),
            "video track timeRange=\(d.video)s but real=\(real)s, track duration inflated"
        )
    }

    /// A/V SYNC regression (BUG #akm19m): audio was out of sync from the start and
    /// drifted further over time. Proven cause: the per-segment muxer dropped audio
    /// packets that arrived past seg_end while waiting for the closing video keyframe,
    /// leaving a gap at every segment boundary (measured: source 5874 eac3 packets vs
    /// 4545 muxed; audio reached only 145s of 188s). The audio track must span the
    /// whole movie (≈ the video duration), not fall short.
    func testAudioTrackSpansFullDuration() throws {
        if Self.ffmpegMissing { throw XCTSkip("ffmpeg not found; cannot generate fixture") }
        let mkv = try XCTUnwrap(Self.mkvPath, "fixture MKV was not generated")

        let session = try GMStreamSession(
            source: XCTUnwrap(GMFileByteSource(path: mkv)),
            targetSegmentSeconds: 2.0
        )
        let real = session.duration
        let loader = try GMResourceLoaderDelegate(session: session)
        let d = try avDurations(loader.assembledBytes)

        // Audio must reach the movie end. A dropped-packet gap per ~2s segment makes
        // it fall materially short (the bug left audio at ~77% of the video length).
        XCTAssertGreaterThan(d.audio, 0, "no audio track")
        XCTAssertEqual(
            d.audio, d.video, accuracy: max(0.5, d.video * 0.02),
            "audio track=\(d.audio)s but video=\(d.video)s, audio packets dropped at segment boundaries (A/V desync)"
        )
    }

    /// SEEK regression: after seeking to a real mid-movie time, AVFoundation must
    /// random-access there and decode frames near that time (not past content).
    func testResourceLoaderSeekDecodesFrames() throws {
        if Self.ffmpegMissing { throw XCTSkip("ffmpeg not found; cannot generate fixture") }
        let mkv = try XCTUnwrap(Self.mkvPath, "fixture MKV was not generated")

        let session = try GMStreamSession(
            source: XCTUnwrap(GMFileByteSource(path: mkv)),
            targetSegmentSeconds: 2.0
        )
        let duration = session.duration
        let loader = try GMResourceLoaderDelegate(session: session)
        let data = loader.assembledBytes

        // Seek to ~70% through the REAL movie and require frames decoded near that time.
        let seekTime = duration * 0.7
        let (frames, firstPTS) = try decodeFromSeek(data, seekTime: seekTime)
        XCTAssertGreaterThan(
            frames, 0,
            "seek to \(seekTime)s of \(duration)s decoded NO frames, black screen on seek"
        )
        XCTAssertEqual(
            firstPTS, seekTime, accuracy: 2.0,
            "seek landed at \(firstPTS)s, expected ~\(seekTime)s"
        )
    }

    /// THE regression test: the resource-loader stream must decode through the whole
    /// movie under AVFoundation, not stall at the first segment boundary.
    func testResourceLoaderDecodesEntireStream() throws {
        if Self.ffmpegMissing { throw XCTSkip("ffmpeg not found; cannot generate fixture") }
        let mkv = try XCTUnwrap(Self.mkvPath, "fixture MKV was not generated")

        let session = try GMStreamSession(
            source: XCTUnwrap(GMFileByteSource(path: mkv)),
            targetSegmentSeconds: 2.0
        )
        let duration = session.duration
        XCTAssertGreaterThan(session.segmentCount, 2, "need a multi-segment movie to exercise boundaries")

        let loader = try GMResourceLoaderDelegate(session: session)
        let (frames, lastPTS) = try decodeAllFrames(loader.assembledBytes)

        // Expect frames across the WHOLE movie. 30fps * 12s ≈ 360 frames; allow slack.
        // The bug yields ~60 frames / lastPTS ≈ 2s, so these bounds catch it cleanly.
        XCTAssertGreaterThan(
            lastPTS,
            duration - 2.0,
            "AVFoundation stopped at \(lastPTS)s of \(duration)s, stalled after the first fragment"
        )
        XCTAssertGreaterThan(
            frames,
            Int(duration * 20),
            "decoded only \(frames) frames for a \(duration)s movie, first-fragment stall"
        )
    }

    /// ROOT-CAUSE pinpoint (proven by experiment, NOT the mfra red herring): each
    /// fragment carries an `mfhd` (Movie Fragment Header) with a `sequence_number`.
    /// ISOBMFF requires these to INCREASE across the file. Our per-segment muxer is a
    /// fresh ffmpeg context per segment, so it RESETS sequence_number to 1 at every
    /// segment boundary (observed: 1,2,1,2,1,... for 2 fragments/segment). AVFoundation
    /// stops decoding at the first fragment whose sequence_number is not greater than
    /// the previous one, which is exactly where playback freezes (~one segment in).
    /// FFmpeg ignores the regression and decodes everything, which is why byte-level
    /// checks looked fine. (Stripping mfra was tested and does NOT fix it.)
    func testFragmentSequenceNumbersAreMonotonic() throws {
        if Self.ffmpegMissing { throw XCTSkip("ffmpeg not found; cannot generate fixture") }
        let mkv = try XCTUnwrap(Self.mkvPath, "fixture MKV was not generated")

        let session = try GMStreamSession(
            source: XCTUnwrap(GMFileByteSource(path: mkv)),
            targetSegmentSeconds: 2.0
        )
        let loader = try GMResourceLoaderDelegate(session: session)
        let seqs = Self.mfhdSequenceNumbers(loader.assembledBytes)

        XCTAssertGreaterThan(seqs.count, 2, "need multiple fragments to check monotonicity")
        var firstBreak = -1
        for k in 1 ..< seqs.count where seqs[k] <= seqs[k - 1] {
            firstBreak = k
            break
        }
        XCTAssertEqual(
            firstBreak, -1,
            "mfhd sequence_number is not strictly increasing (resets at fragment \(firstBreak)). "
                + "AVFoundation stops decoding there. Sequence: \(seqs)"
        )
    }

    /// Separate (non-fatal) defect guard: a fresh per-segment muxer can emit a
    /// negative audio baseMediaDecodeTime (encoder pre-roll/priming) which, stored as
    /// the unsigned 64-bit tfdt, wraps to ~2^64. The reference single-pass fMP4 has 0.
    /// This does NOT cause the video stall (proven: fixing mfhd seq alone restores full
    /// decode), but a ~18-quintillion tfdt is wrong and can glitch audio start, so guard
    /// it. Any tfdt above the movie duration (in its track timescale, times a slack
    /// factor) is treated as a wrapped-negative value.
    func testNoFragmentHasWildlyOutOfRangeTFDT() throws {
        if Self.ffmpegMissing { throw XCTSkip("ffmpeg not found; cannot generate fixture") }
        let mkv = try XCTUnwrap(Self.mkvPath, "fixture MKV was not generated")

        let session = try GMStreamSession(
            source: XCTUnwrap(GMFileByteSource(path: mkv)),
            targetSegmentSeconds: 2.0
        )
        let loader = try GMResourceLoaderDelegate(session: session)
        let bad = Self.tfdtValues(loader.assembledBytes).filter { $0 > UInt64(1) << 60 }
        XCTAssertTrue(
            bad.isEmpty,
            "found \(bad.count) fragment(s) with a wrapped-negative tfdt (e.g. \(bad.first ?? 0)); "
                + "a fresh per-segment muxer emitted a negative baseMediaDecodeTime."
        )
    }

    /// Every tfdt baseMediaDecodeTime in the file (both tracks, all fragments).
    private static func tfdtValues(_ d: Data) -> [UInt64] {
        var vals: [UInt64] = []
        func walk(_ start: Int, _ end: Int) {
            var i = start
            while i + 8 <= end {
                let sz = Int(d[i]) << 24 | Int(d[i + 1]) << 16 | Int(d[i + 2]) << 8 | Int(d[i + 3])
                if sz < 8 { break }
                let type = String(bytes: d[(i + 4) ..< (i + 8)], encoding: .ascii) ?? ""
                if type == "moof" || type == "traf" {
                    walk(i + 8, min(i + sz, end))
                } else if type == "tfdt", i + 16 <= end {
                    let ver = d[i + 8]
                    if ver == 1 {
                        var v: UInt64 = 0
                        for k in 0 ..< 8 {
                            v = (v << 8) | UInt64(d[i + 12 + k])
                        }
                        vals.append(v)
                    } else {
                        let o = i + 12
                        vals.append(UInt64(UInt32(d[o]) << 24 | UInt32(d[o + 1]) << 16 | UInt32(d[o + 2]) << 8 | UInt32(d[o + 3])))
                    }
                }
                i += sz
            }
        }
        walk(0, d.count)
        return vals
    }

    /// Extract each fragment's mfhd sequence_number, in file order.
    private static func mfhdSequenceNumbers(_ d: Data) -> [UInt32] {
        var seqs: [UInt32] = []
        for box in topLevelBoxes(d) where box.type == "moof" {
            let s = box.offset
            let e = min(box.offset + box.size, d.count)
            // Find 'mfhd' within this moof; sequence_number is the u32 after ver/flags.
            var j = s
            while j + 8 <= e {
                let t = String(bytes: d[(j + 4) ..< (j + 8)], encoding: .ascii) ?? ""
                if t == "mfhd", j + 16 <= e {
                    let o = j + 12
                    seqs.append(UInt32(d[o]) << 24 | UInt32(d[o + 1]) << 16 | UInt32(d[o + 2]) << 8 | UInt32(d[o + 3]))
                    break
                }
                if t == "mfhd" { break }
                j += 4
            }
        }
        return seqs
    }

    /// Parse the top-level box type sequence (type, offset, size).
    private static func topLevelBoxes(_ d: Data) -> [(type: String, offset: Int, size: Int)] {
        var out: [(String, Int, Int)] = []
        var i = 0
        let n = d.count
        while i + 8 <= n {
            let size = Int(d[i]) << 24 | Int(d[i + 1]) << 16 | Int(d[i + 2]) << 8 | Int(d[i + 3])
            let type = String(bytes: d[(i + 4) ..< (i + 8)], encoding: .ascii) ?? "????"
            out.append((type, i, size))
            if size < 8 { break }
            i += size
        }
        return out
    }
}
